name: "Cleaning up Stale Branches"
description: "Automatically find up stale branches and cleanup them"
author: "Siwon Choi"

inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
    required: false
    default: '${{ github.token }}'
  days-before-stale:
    description: 'The age in days before a branch is considered stale. Can be passed in using `30`.'
    required: false
    default: 30
  days-before-delete:
    description: 'The age in days after a branch is considered stale, before it is deleted. Can be passed in using `7`.'
    required: false
    default: 7
  ignoring-branches:
    description: 'Comma separated list of branches that should be ignored. Default is `main,master`.'
    required: false
    default: "main,master"
  ignore-branches-pattern:
    description: 'Pattern of branches that should be ignored.'
    required: false
    default: "release/*"
  stale-branch-message:
    description: 'The message to post on webhook when a branch is considered stale.'
    required: false
    default: "These branches were considered stale and will be deleted in a few days."
  delete-branch-message:
    description: 'The message to post on webhook when a branch is deleted.'
    required: false
    default: "These branches were deleted because they were stale."
  dry-run:
    description: 'If true, the action will only log the branches that would be deleted.'
    required: false
    default: false
  use-webhook:
    description: 'If true, the action will send a message to webhook when branches are considered for deletion or deleted.'
    required: false
    default: false
  webhook-url:
    description: 'Webhook URL to send a message when branches are considered for deletion or deleted. Recommend to use `{{ secrets.WEBHOOK_URL }}`.'
    required: false
    default: ""
  webhook-type:
    description: 'The type of webhook to send. Can be `discord` or `slack`.'
    required: false
    default: "discord"

outputs:
  staled-branches:
    description: 'The list of branches that were considered stale.'
  deleted-branches:
    description: 'The list of branches that were deleted.'

branding:
  icon: "trash"
  color: "red"

runs:
  using: "node20"
  main: "dist/index.js"
